version: '3.9'

services:
  db:
    image: postgres:16
    container_name: agrodroid-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: vinedosdb
    ports:
      - "5432:5432"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  app:
    build: ./app
    container_name: agrodroid-api
    ports:
      - "3000:3000"

    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: admin
      DB_PASSWORD: admin123
      DB_NAME: vinedosdb
      JWT_SECRET: mipalabrasecreta

    depends_on:
      - db

web:
  build: ./web
  container_name: agrodroid-web
  ports:
    - "5173:5173"
  depends_on:
    - app