version: '3.9'

services:
  db:
    image: postgres:16
    container_name: agrodroid-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  app:
    build: ./app
    container_name: agrodroid-api
    ports:
      - "3000:3000"
    volumes:
      - ./app:/app
      - /app/node_modules
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      JWT_SECRET: ${JWT_SECRET}

    depends_on:
      - db

  web:
    build: ./web
    container_name: agrodroid-web
    ports:
      - "5173:5173"
    volumes:
      - ./web/src:/app/src
      - ./web/index.html:/app/index.html
    depends_on:
      - app
